# Generated by Django 4.0.2 on 2022-05-18 05:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cli_uuid', models.CharField(max_length=64)),
                ('cli_first_name', models.CharField(max_length=64)),
                ('cli_last_name', models.CharField(max_length=64)),
                ('cli_age', models.IntegerField(default=0)),
                ('cli_document', models.CharField(default=None, max_length=64)),
                ('cli_document_type', models.CharField(max_length=16)),
                ('cli_cellphone', models.CharField(max_length=32)),
                ('cli_email', models.CharField(max_length=64)),
                ('cli_direction', models.CharField(max_length=248)),
            ],
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_uuid', models.CharField(max_length=64)),
                ('max_capacity', models.IntegerField(default=0)),
                ('current_capacity', models.IntegerField(default=0)),
                ('temperature', models.IntegerField(default=0)),
                ('type', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ContainerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_type_id', models.IntegerField(default=0)),
                ('type', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cli_uuid', models.CharField(max_length=64)),
                ('container_uuid', models.CharField(max_length=64)),
                ('prod_uuid', models.CharField(max_length=64)),
                ('prod_name', models.CharField(max_length=64)),
                ('prod_register_date', models.DateTimeField(default=datetime.datetime.now)),
                ('prod_harvest_date', models.DateField()),
                ('prod_type', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tru_uuid', models.CharField(max_length=64, null=True)),
                ('tru_max_capacity', models.IntegerField()),
                ('tru_actual_capacity', models.IntegerField()),
                ('tru_location', models.CharField(max_length=84)),
                ('tru_status', models.CharField(max_length=32)),
                ('tru_placa', models.CharField(max_length=32)),
                ('tru_brand', models.CharField(max_length=32)),
                ('tru_model', models.CharField(max_length=32)),
                ('tru_color', models.CharField(max_length=32)),
                ('tru_truck_number', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='TruckType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truT_id', models.IntegerField()),
                ('truT_type', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_uuid', models.CharField(max_length=64)),
                ('user_name', models.CharField(max_length=32, null=True)),
                ('user_password', models.CharField(max_length=128)),
                ('user_email', models.CharField(max_length=64)),
                ('user_direction', models.CharField(max_length=248)),
                ('user_cellphone', models.CharField(max_length=32)),
                ('user_role', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userT_id', models.IntegerField()),
                ('userT_role', models.CharField(max_length=32)),
            ],
        ),
    ]
