# Generated by Django 4.0.4 on 2022-06-02 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prod_qty',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
